name: Atualizar README

on:
  schedule:
    - cron: "0 */1 * * *"  # A cada 1 horas
  workflow_dispatch:

jobs:
  update:
    runs-on: ubuntu-latest
    steps:
      - name: Atualizar cache dos cards
        run: |
          curl -s "https://github-readme-stats.vercel.app/api?username=Caio13Vinni" > /dev/null
          curl -s "https://github-readme-stats.vercel.app/api/top-langs/?username=Caio13Vinni" > /dev/null
